/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cafe(props) {
  const { nodes, materials } = useGLTF("src/assets/models/cafe_gltf.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.002"]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.black}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.004"]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.011"]}
        scale={[3.781, 1.769, 3.781]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.railing.geometry}
        material={materials["Material.011"]}
        scale={[3.781, 1.769, 3.781]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cup.geometry}
        material={materials["Material.004"]}
        position={[-0.556, 0.991, 0.486]}
        scale={[2.128, 2.128, 3.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials.black}
        position={[-0.556, 1.138, 0.241]}
        scale={[2.128, 2.128, 3.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials["Material.004"]}
        position={[1.8, 5.796, 0.801]}
        rotation={[Math.PI / 2, 0, -1.576]}
        scale={0.737}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={materials.black}
          position={[0, -0.041, 0]}
          rotation={[1.571, -1.566, 1.571]}
          scale={0.687}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={materials.black}
          position={[1.567, -0.033, 0]}
          rotation={[1.571, -1.566, 1.571]}
          scale={0.687}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={materials.black}
          position={[3.1, -0.025, 0]}
          rotation={[1.571, -1.566, 1.571]}
          scale={0.687}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials["Material.004"]}
          position={[-1.584, -0.008, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004.geometry}
            material={materials.Material}
            position={[2.36, -3.186, 6.323]}
            rotation={[1.571, -1.566, -3.142]}
            scale={[2.889, 2.889, 4.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane005.geometry}
            material={materials.black}
            position={[2.36, -3.186, 6.323]}
            rotation={[1.571, -1.566, -3.142]}
            scale={[2.889, 2.889, 4.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006.geometry}
            material={materials["Material.004"]}
            position={[2.36, -3.186, 6.323]}
            rotation={[1.571, -1.566, -Math.PI]}
            scale={[2.889, 2.889, 4.081]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane007.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane008.geometry}
              material={materials["Material.007"]}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane010.geometry}
            material={materials["Material.010"]}
            position={[2.36, -3.186, 6.323]}
            rotation={[1.571, -1.566, -3.142]}
            scale={[2.889, 2.889, 4.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012.geometry}
            material={materials.black}
            position={[2.36, -3.186, 6.323]}
            rotation={[1.571, -1.566, -3.142]}
            scale={[2.65, 2.65, 3.744]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane017.geometry}
            material={materials.black}
            position={[0, -0.041, 0]}
            rotation={[1.571, -1.566, 1.571]}
            scale={0.687}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text002.geometry}
          material={materials["Material.004"]}
          position={[1.567, 0.008, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003.geometry}
          material={materials["Material.004"]}
          position={[3.1, 0.015, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials["Material.010"]}
        position={[3.143, 0.984, -2.912]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials["Material.011"]}
        position={[3.143, 0.984, -2.912]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials["Material.001"]}
        position={[-0.606, 6.514, 0.166]}
        scale={1.676}
      />
    </group>
  );
}

useGLTF.preload("src/assets/models/cafe_gltf.gltf");
